# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MLKit Starter Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MLKit Starter Project
pod 'Firebase/Core'
pod 'Firebase/MLVision'
pod 'Firebase/MLVisionTextModel'
pod 'Firebase/MLVisionFaceModel'
pod 'Firebase/MLVisionBarcodeModel'
pod 'Firebase/MLVision'
pod 'Firebase/MLVisionLabelModel'
pod 'lottie-ios'
pod 'SteviaLayout'
end
