# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'W7D2-firebase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for W7D2-firebase
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Database'

end
