# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'W4D5-MaterialDesign' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for W4D5-MaterialDesign
	pod 'MaterialComponents'
	pod 'SDWebImage', '~>3.8'
	
end
