//
//  Names.m
//  W3D2
//
//  Created by Jason Liang on 9/19/17.
//  Copyright © 2017 jason. All rights reserved.
//

#import "Names.h"

@implementation Names

+ (NSArray *)getNames {
  NSArray *names = @[@"Max",
                     @"Charlie",
                     @"Buddy",
                     @"Cooper",
                     @"Jack",
                     @"Rocky",
                     @"Bear",
                     @"Duke",
                     @"Toby",
                     @"Tucker",
                     @"Oliver",
                     @"Bentley",
                     @"Milo",
                     @"Teddy",
                     @"Jake",
                     @"Leo",
                     @"Jax",
                     @"Dexter",
                     @"Zeus",
                     @"Louie",
                     @"Riley",
                     @"Winston",
                     @"Buster",
                     @"Murphy",
                     @"Jackson",
                     @"Bailey",
                     @"Harley",
                     @"Gus",
                     @"Lucky",
                     @"Oscar",
                     @"Henry",
                     @"Cody",
                     @"Hank",
                     @"Sam",
                     @"Baxter",
                     @"Ollie",
                     @"Diesel",
                     @"Bruno",
                     @"Bandit",
                     @"Beau",
                     @"Gizmo",
                     @"Moose",
                     @"Finn",
                     @"Sammy",
                     @"Blue",
                     @"Marley",
                     @"Loki",
                     @"Brody",
                     @"Jasper",
                     @"Ace",
                     @"Thor",
                     @"Shadow",
                     @"Rocco",
                     @"Apollo",
                     @"Roscoe",
                     @"George",
                     @"Scout",
                     @"Bo",
                     @"Rex",
                     @"Tank",
                     @"Tyson",
                     @"Rusty",
                     @"Otis",
                     @"Koda",
                     @"Luke",
                     @"Simba",
                     @"Gunner",
                     @"Romeo",
                     @"Hunter",
                     @"Joey",
                     @"Rudy",
                     @"Boomer",
                     @"Ziggy",
                     @"Copper",
                     @"Maverick",
                     @"Oreo",
                     @"Prince",
                     @"Frankie",
                     @"Bruce",
                     @"Samson",
                     @"Peanut",
                     @"Benny",
                     @"Brutus",
                     @"Ranger",
                     @"Chester",
                     @"Chase",
                     @"Chance",
                     @"Kobe",
                     @"Brady",
                     @"Coco",
                     @"Chico",
                     @"Chewy",
                     @"Bubba",
                     @"Benji",
                     @"Mickey",
                     @"Rufus",
                     @"King",
                     @"Archie",
                     @"Cash",
                     @"Walter"
];
  return names;
}

@end
